version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  gateway-service:
    image: gateway-service:test
    container_name: gateway_service_test
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - Services__LibraryService=http://library-service:8060
      - Services__RatingService=http://rating-service:8050
      - Services__ReservationService=http://reservation-service:8070

  library-service:
    image: library-service:test
    container_name: library_service_test
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8060:8060"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8060
      - ConnectionStrings__DefaultConnection=Host=LibraryServiceDb;Port=5432;Database=postgres;Username=postgres;Password=postgres

  rating-service:
    image: rating-service:test
    container_name: rating_service_test
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8050:8050"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8050
      - ConnectionStrings__DefaultConnection=Host=RatingServiceDb;Port=5432;Database=postgres;Username=postgres;Password=postgres

  reservation-service:
    image: reservation-service:test
    container_name: reservation_service_test
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8070:8070"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8070
      - ConnectionStrings__DefaultConnection=Host=ReservationServiceDb;Port=5432;Database=postgres;Username=postgres;Password=postgres

networks:
  default:
    name: rsoi_test_network