CREATE DATABASE "LibraryServiceDb";

\c "LibraryServiceDb";
-- Создание таблицы Books
CREATE TABLE "Books" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    book_uid uuid NOT NULL,
    name text NOT NULL,
    author text NULL,
    genre text NULL,
    condition integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_Books" PRIMARY KEY (id)
);

-- Создание таблицы Libraries
CREATE TABLE "Libraries" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    library_uid uuid NOT NULL,
    name text NOT NULL,
    city text NOT NULL,
    address text NOT NULL,
    CONSTRAINT "PK_Libraries" PRIMARY KEY (id)
);

-- Создание таблицы library_books (связующая таблица многие-ко-многим)
CREATE TABLE library_books (
    book_id integer NOT NULL,
    library_id integer NOT NULL,
    available_count integer NOT NULL,
    CONSTRAINT "PK_library_books" PRIMARY KEY (library_id, book_id)
);

-- Создание индексов для таблицы Books
CREATE UNIQUE INDEX "IX_Books_id" ON "Books" (id);

-- Создание индексов для таблицы Libraries
CREATE UNIQUE INDEX "IX_Libraries_id" ON "Libraries" (id);

-- Создание индексов для таблицы library_books
CREATE INDEX "IX_library_books_book_id" ON library_books (book_id);
CREATE UNIQUE INDEX "IX_library_books_library_id_book_id" ON library_books (library_id, book_id);

-- Создание внешних ключей для таблицы library_books
ALTER TABLE library_books ADD CONSTRAINT "FK_library_books_Books_book_id" 
    FOREIGN KEY (book_id) REFERENCES "Books" (id) ON DELETE CASCADE;

ALTER TABLE library_books ADD CONSTRAINT "FK_library_books_Libraries_library_id" 
    FOREIGN KEY (library_id) REFERENCES "Libraries" (id) ON DELETE CASCADE;

-- Заполнение таблицы Libraries
INSERT INTO "Libraries" (id, library_uid, name, city, address)
VALUES (1, '83575e12-7ce0-48ee-9931-51919ff3c9ee'::uuid, 'Библиотека имени 7 Непьющих', 'Москва', '2-я Бауманская ул., д.5, стр.1');

-- Заполнение таблицы Books
INSERT INTO "Books" (id, book_uid, name, author, genre, condition)
VALUES (1, 'f7cdc58f-2caf-4b15-9727-f89dcc629b27'::uuid, 'Краткий курс C++ в 7 томах', 'Бьерн Страуструп', 'Научная фантастика', 0);

-- Заполнение таблицы library_books
INSERT INTO library_books (book_id, library_id, available_count)
VALUES (1, 1, 1);

CREATE DATABASE "RatingServiceDb";
\c "RatingServiceDb";

-- Создание таблицы rating
CREATE TABLE rating (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    username text NOT NULL,
    stars integer NOT NULL,
    CONSTRAINT "PK_rating" PRIMARY KEY (id)
);

-- Создание индексов
CREATE UNIQUE INDEX "IX_rating_id" ON rating (id);
CREATE UNIQUE INDEX "IX_rating_username" ON rating (username);

INSERT INTO rating (id, username, stars) VALUES (1, 'Test Max', 75);