name: Microservices CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Services
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - { name: 'gateway', path: 'GatewayService', port: '8080' }
          - { name: 'library', path: 'LibraryService', port: '8060' }
          - { name: 'rating', path: 'RatingService', port: '8050' }
          - { name: 'reservation', path: 'ReservationService', port: '8070' }
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Run Unit Tests
        run: |
          cd services/${{ matrix.service.path }}
          if [ -d "src/${{ matrix.service.path }}.Tests" ]; then
            dotnet test src/${{ matrix.service.path }}.Tests/ --configuration Release --verbosity normal
          else
            echo "No tests found for ${{ matrix.service.name }}, skipping..."
          fi
        continue-on-error: true

      - name: Publish ${{ matrix.service.name }}
        run: |
          cd services/${{ matrix.service.path }}
          dotnet publish src/${{ matrix.service.path }}.Server/${{ matrix.service.path }}.Server.csproj \
            -c Release \
            -o ${{ matrix.service.path }}ServicePublish/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./services/${{ matrix.service.path }}
          file: ./services/${{ matrix.service.path }}/Dockerfile
          tags: ${{ matrix.service.name }}-service:test
          outputs: type=docker,dest=/tmp/${{ matrix.service.name }}-service.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.service.name }}-service
          path: /tmp/${{ matrix.service.name }}-service.tar
          retention-days: 1

  integration-tests:
    name: Integration Tests
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: /tmp/images

      - name: Load Docker images
        run: |
          docker load --input /tmp/images/gateway-service/gateway-service.tar
          docker load --input /tmp/images/library-service/library-service.tar
          docker load --input /tmp/images/rating-service/rating-service.tar
          docker load --input /tmp/images/reservation-service/reservation-service.tar

      - name: Start services
        run: docker-compose -f docker-compose.test.yml up -d

      - name: Wait for services to be healthy
        run: |
          chmod +x ./Scripts/wait-script.sh
          chmod +x ./Scripts/wait-for.sh
          export WAIT_PORTS="8080,8060,8050,8070"
          ./Scripts/wait-script.sh

      - name: Check services status
        run: |
          echo "=== Docker Compose Status ==="
          docker-compose -f docker-compose.test.yml ps

      - name: Show logs on failure
        if: failure()
        run: |
          echo "=== Postgres Logs ==="
          docker-compose -f docker-compose.test.yml logs postgres
          echo "=== Gateway Logs ==="
          docker-compose -f docker-compose.test.yml logs gateway-service
          echo "=== Library Logs ==="
          docker-compose -f docker-compose.test.yml logs library-service
          echo "=== Rating Logs ==="
          docker-compose -f docker-compose.test.yml logs rating-service
          echo "=== Reservation Logs ==="
          docker-compose -f docker-compose.test.yml logs reservation-service

      - name: Run Postman Tests
        uses: matt-ball/newman-action@master
        with:
          collection: postman/[inst] Lab1.postman_collection.json
          environment: postman/[inst][local] Lab1.postman_environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - name: Cleanup
        if: always()
        run: docker-compose -f docker-compose.test.yml down -v

      - name: Autograding
        uses: education/autograding@v1
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 1
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"
        continue-on-error: true